import {PrivateApiClient, PublicApiClient} from "./api-client";

export const alice = PrivateApiClient('eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IkFQUF9VU0VSIiwic3ViIjoiODQ0MjhkMDgtNjAzMS00MDBiLTg0ZDEtMzNmYzg1NjE5OWNhIiwiaWF0IjoxNzYyNzA1Mzc0LCJleHAiOjUzNjI3MDUzNzR9.znjKTlccMJWJww1HbvyHDIMS8tz65g_bzbvlgh8jZ0A');

export const bob = PrivateApiClient('eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IkFQUF9VU0VSIiwic3ViIjoiMzYzY2FmYjUtNjYwOC00M2Y5LTg1ZDQtOTU3MDI3Njk4NDA4IiwiaWF0IjoxNzYyNzA1NDM0LCJleHAiOjUzNjI3MDU0MzR9.0BZkSlov13ApIWoDSLaXv7b5wkf3cO9NBDDr_Nc__e8');

export const admin = PrivateApiClient('eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IkFETUlOX1VTRVIiLCJzdWIiOiIwYTNjZWJhYS05NzRkLTQ2ZjUtYWI0ZC1lNTczZmEwNjdlZDkiLCJpYXQiOjE3NjI3MDU0NjgsImV4cCI6NTM2MjcwNTQ2OH0.v8OOMBnsTGbNwnLAut9GkSkODLjWBS4vqwu5vBiF2P4');

export const publicUser = PublicApiClient();