import {PrivateApiClient, PublicApiClient} from "./api-client";

export const alice = PrivateApiClient('eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IkFQUF9VU0VSIiwic3ViIjoiNzI0MzliYjctYTczOS00MmJkLTgzMjctMGJhZTg0OWYwNjU2IiwiaWF0IjoxNzYzODg0OTQ5LCJleHAiOjUzNjM4ODQ5NDl9.0NOG9OCrHicbekMVhgITQDuubLxF0n97Hf0P3foUWnY');

export const bob = PrivateApiClient('eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IkFQUF9VU0VSIiwic3ViIjoiNDVhOTFkOTctZjI1Mi00Njg4LWJiZmYtNGFkM2VkMTY5YTIwIiwiaWF0IjoxNzYzODg1MDAyLCJleHAiOjUzNjM4ODUwMDJ9.kNSbcTzU7oMuF39Vi8pjvo9LgYfPAHdMs1gMz2Qmm0Q');

export const admin = PrivateApiClient('eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6IkFETUlOX1VTRVIiLCJzdWIiOiJkM2IwNzM4NC1kOWExLTRmNWQtOGMyZC02YzhlMGYyZjRmNWEiLCJpYXQiOjE3NjM4ODUwNTEsImV4cCI6NTM2Mzg4NTA1MX0.RkZK0QMhm7NxuVFxIDYkoiHXwxs8iA3mVMgnAPS_GRE');

export const publicUser = PublicApiClient();