/**
 * My API
 * OpenAPI documentation for My API
 *
 * The version of the OpenAPI document: 59acdd34ea678de65cbe0a25f66df8cefdf5050b
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TestEntityLogisticProp } from './testEntityLogisticProp';
import { TestEntityProperty } from './testEntityProperty';


export interface TestEntityDto { 
    title: string;
    description?: string;
    category: TestEntityDtoCategoryEnum;
    logisticProp: TestEntityLogisticProp;
    available: boolean;
    borrows: Set<TestEntityProperty>;
}
export enum TestEntityDtoCategoryEnum {
    BOOK = 'BOOK',
    ELECTRONICS = 'ELECTRONICS',
    CLOTHING = 'CLOTHING',
    TOY = 'TOY'
};



