/**
 * My API
 * OpenAPI documentation for My API
 *
 * The version of the OpenAPI document: 59acdd34ea678de65cbe0a25f66df8cefdf5050b
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WipStepValidationRes { 
    isValid: boolean;
    errorType?: WipStepValidationResErrorTypeEnum;
    errorMessage?: string;
}
export enum WipStepValidationResErrorTypeEnum {
    MISSING_STEPS = 'MISSING_STEPS',
    MISSING_REQUIRED_FIELDS = 'MISSING_REQUIRED_FIELDS',
    ONLY_ONE_FIRST_STEP_REQUIRED = 'ONLY_ONE_FIRST_STEP_REQUIRED',
    AT_LEAST_ONE_LAST_STEP_REQUIRED = 'AT_LEAST_ONE_LAST_STEP_REQUIRED',
    INVALID_STEP_CONNECTIONS = 'INVALID_STEP_CONNECTIONS'
};



